# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24ada8a5d2a8f8ad85bd9f74fe3290ea22544107acffa6c6d385816a36e6b390d9adcd2eb2d3b2e80057d8b53e73fea96635cd8148d0f14f3ed67df1040c5417

test:
  secret_key_base: 2e2e24edd0ad332b8b362bb3c4b1c9f8c724fab04acc5dc625af5fdc277739f1d02ba30f6baed26ec77f7a36c7f8465a3068baa0ae0871a1c59d440a41131d6e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
